<?php

namespace Database\Seeders;

use App\Models\Printer;
use App\Models\PrintServer;
use Illuminate\Database\Seeder;

class PrinterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $server = PrintServer::first();

        $printer = new Printer;
        $printer->uri = 'debug://';
        $printer->name = 'DEBUG';
        $printer->raw_languages_supported = ['*'];
        $server->Printers()->save($printer);

        $printer = new Printer;
        $printer->uri = 'lpd://192.168.9.20/OKI-ML3320?timeout=10&tries=10';
        $printer->name = 'OKI-ML3320 (LPD)';
        $printer->raw_languages_supported = ['microline'];
        $server->Printers()->save($printer);

        $printer = new Printer;
        $printer->uri = 'socket://192.168.9.20:9101?timeout=10';
        $printer->name = 'OKI-ML3320 (RAW)';
        $printer->raw_languages_supported = ['microline'];
        $server->Printers()->save($printer);

        $printer = new Printer;
        $printer->uri = 'cups://OKI_ML3320';
        $printer->name = 'OKI-ML3320 (CUPS)';
        $printer->raw_languages_supported = ['microline'];
        $printer->ppd_support = true;
        $printer->ppd_options = [
            'PageSize' => [
                'name' => 'Media Size',
                'values' => [
                    'Letter' => 'US Letter',
                    'Legal' => 'US Legal',
                    'A4' => 'A4',
                    'FanFoldUS' => 'US Fanfold',
                    'Custom.WIDTHxHEIGHT' => 'Custom',
                ],
                'default' => 'A4',
            ],
            'Resolution' => [
                'name' => 'Resolution',
                'values' => [
                    '60x72dpi' => '60x72dpi',
                    '120x72dpi' => '120x72dpi',
                    '240x72dpi' => '240x72dpi',
                ],
                'default' => '240x72dpi',
            ],
        ];
        $printer->ppd_options_layout = [
            [
                'name' => 'General',
                'options' => [
                    'PageSize',
                    'Resolution',
                ],
            ],
        ];
        $server->Printers()->save($printer);

        $printer = new Printer;
        $printer->uri = 'cups://TM_T88V';
        $printer->name = 'Epson TM-T88V (CUPS)';
        $printer->raw_languages_supported = ['escpos'];
        $printer->ppd_support = true;
        $printer->ppd_options = [
            'PageSize' => [
                'name' => 'Media Size',
                'values' => [
                    'RP80x297' => 'Roll Paper 80 x 297 mm',
                    'RP58x297' => 'Roll Paper 58 x 297 mm',
                    'A4' => 'A4',
                    'Letter' => 'Letter',
                    'Legal' => 'Legal',
                    'Custom.WIDTHxHEIGHT' => 'Custom',
                ],
                'default' => 'RP80x297',
            ],
            'Resolution' => [
                'name' => 'Resolution',
                'values' => [
                    '180x180dpi' => '180x180dpi',
                ],
                'default' => '180x180dpi',
            ],
            'TmtSpeed' => [
                'name' => 'Printing Speed',
                'values' => [
                    'Auto' => 'Use the printer settings',
                    '1' => '1st (Fast)',
                    '2' => '2nd',
                    '3' => '3rd',
                    '4' => '4th (Slow)',
                ],
                'default' => '4',
            ],
            'TmtPaperReduction' => [
                'name' => 'Paper Reduction',
                'values' => [
                    'Off' => 'None',
                    'Top' => 'Top margin',
                    'Bottom' => 'Bottom margin',
                    'Both' => 'Top & Bottom margins',
                ],
                'default' => 'Both',
            ],
            'TmtPaperSource' => [
                'name' => 'Paper Source',
                'values' => [
                    'DocFeedCut' => 'Document [Feed, Cut]',
                    'DocFeedNoCut' => 'Document [Feed, NoCut]',
                    'DocNoFeedCut' => 'Document [NoFeed, Cut]',
                    'DocNoFeedNoCut' => 'Document [NoFeed, NoCut]',
                    'PageFeedCut' => 'Page [Feed, Cut]',
                    'PageFeedNoCut' => 'Page [Feed, NoCut]',
                    'PageNoFeedCut' => 'Page [NoFeed, Cut]',
                ],
                'default' => 'DocFeedCut',
            ],
            'TmtBuzzerControl' => [
                'name' => 'Buzzer',
                'values' => [
                    'Off' => 'Not used',
                    'Before' => 'Sound before printing',
                    'After' => 'Sound after printing',
                ],
                'default' => 'Off',
            ],
            'TmtSoundPattern' => [
                'name' => 'Sound Pattern',
                'values' => [
                    'Internal' => 'Internal buzzer',
                    'A' => 'Option buzzer (Pattern A)',
                    'B' => 'Option buzzer (Pattern B)',
                    'C' => 'Option buzzer (Pattern C)',
                    'D' => 'Option buzzer (Pattern D)',
                    'E' => 'Option buzzer (Pattern E)',
                ],
                'default' => 'Internal',
            ],
            'TmtBuzzerRepeat' => [
                'name' => 'Buzzer Repeat',
                'values' => [
                    '1' => '1',
                    '2' => '2',
                    '3' => '3',
                    '5' => '5',
                ],
                'default' => '1',
            ],
            'TmtDrawer1' => [
                'name' => 'Cash Drawer #1',
                'values' => [
                    'Off' => 'Does not open',
                    'Before' => 'Open before printing',
                    'After' => 'Open after printing',
                ],
                'default' => 'Off',
            ],
            'TmtDrawer2' => [
                'name' => 'Cash Drawer #2',
                'values' => [
                    'Off' => 'Does not open',
                    'Before' => 'Open before printing',
                    'After' => 'Open after printing',
                ],
                'default' => 'Off',
            ],
        ];
        $printer->ppd_options_layout = [
            [
                'name' => 'General',
                'options' => [
                    'PageSize',
                    'Resolution',
                    'TmtSpeed',
                    'TmtPaperReduction',
                    'TmtPaperSource',
                ],
            ],
            [
                'name' => 'Buzzer Control',
                'options' => [
                    'TmtBuzzerControl',
                    'TmtSoundPattern',
                    'TmtBuzzerRepeat',
                ],
            ],
            [
                'name' => 'Cash Drawer Control',
                'options' => [
                    'TmtDrawer1',
                    'TmtDrawer2',
                ],
            ],
        ];
        $server->Printers()->save($printer);

        $printer = new Printer;
        $printer->uri = 'cups://ZD410';
        $printer->name = 'Zebra ZD410 (CUPS)';
        $printer->raw_languages_supported = ['zpl'];
        $printer->ppd_support = true;
        $printer->ppd_options = [
            'PageSize' => [
                'name' => 'Media Size',
                'values' => [
                    'w90h18' => '1.25x0.25"',
                    'w90h162' => '1.25x2.25"',
                    'w108h18' => '1.50x0.25"',
                    'w108h36' => '1.50x0.50"',
                    'w108h72' => '1.50x1.00"',
                    'w108h144' => '1.50x2.00"',
                    'w144h26' => '2.00x0.37"',
                    'w144h36' => '2.00x0.50"',
                    'w144h72' => '2.00x1.00"',
                    'w144h90' => '2.00x1.25"',
                    'w144h288' => '2.00x4.00"',
                    'w144h396' => '2.00x5.50"',
                    'w162h36' => '2.25x0.50"',
                    'w162h90' => '2.25x1.25"',
                    'w162h288' => '2.25x4.00"',
                    'w162h396' => '2.25x5.50"',
                    'w171h396' => '2.38x5.50"',
                    'w180h72' => '2.50x1.00"',
                    'w180h144' => '2.50x2.00"',
                    'w198h90' => '2.75x1.25"',
                    'w216h72' => '3.00x1.00"',
                    'w216h90' => '3.00x1.25"',
                    'w216h144' => '3.00x2.00"',
                    'w216h216' => '3.00x3.00"',
                    'w216h360' => '3.00x5.00"',
                    'w234h144' => '3.25x2.00"',
                    'w234h360' => '3.25x5.00"',
                    'w234h396' => '3.25x5.50"',
                    'w234h419' => '3.25x5.83"',
                    'w234h563' => '3.25x7.83"',
                    'w252h72' => '3.50x1.00"',
                    'w288h72' => '4.00x1.00"',
                    'w288h144' => '4.00x2.00"',
                    'w288h180' => '4.00x2.50"',
                    'w288h216' => '4.00x3.00"',
                    'w288h288' => '4.00x4.00"',
                    'w288h360' => '4.00x5.00"',
                    'w288h432' => '4.00x6.00"',
                    'w288h468' => '4.00x6.50"',
                    'w288h936' => '4.00x13.00"',
                    'w432h72' => '6.00x1.00"',
                    'w432h144' => '6.00x2.00"',
                    'w432h216' => '6.00x3.00"',
                    'w432h288' => '6.00x4.00"',
                    'w432h360' => '6.00x5.00"',
                    'w432h432' => '6.00x6.00"',
                    'w432h468' => '6.00x6.50"',
                    'w576h72' => '8.00x1.00"',
                    'w576h144' => '8.00x2.00"',
                    'w576h216' => '8.00x3.00"',
                    'w576h288' => '8.00x4.00"',
                    'w576h360' => '8.00x5.00"',
                    'w576h432' => '8.00x6.00"',
                    'w576h468' => '8.00x6.50"',
                    'Custom.WIDTHxHEIGHT' => 'Custom',
                ],
                'default' => 'w144h288',
            ],
            'Resolution' => [
                'name' => 'Resolution',
                'values' => [
                    '203dpi' => '203dpi',
                    '300dpi' => '300dpi',
                    '600dpi' => '600dpi',
                ],
                'default' => '600dpi',
            ],
            'zeMediaTracking' => [
                'name' => 'Media Tracking',
                'values' => [
                    'Continuous' => 'Continuous',
                    'Web' => 'Non-continuous (Web sensing)',
                    'Mark' => 'Non-continuous (Mark sensing)',
                ],
                'default' => 'Web',
            ],
            'MediaType' => [
                'name' => 'Media Type',
                'values' => [
                    'Saved' => 'Printer Default',
                    'Thermal' => 'Thermal Transfer Media',
                    'Direct' => 'Direct Thermal Media',
                ],
                'default' => 'Direct',
            ],
            'Darkness' => [
                'name' => 'Darkness',
                'values' => [
                    '-1' => 'Printer Default',
                    '1' => '1',
                    '2' => '2',
                    '3' => '3',
                    '4' => '4',
                    '5' => '5',
                    '6' => '6',
                    '7' => '7',
                    '8' => '8',
                    '9' => '9',
                    '10' => '10',
                    '11' => '11',
                    '12' => '12',
                    '13' => '13',
                    '14' => '14',
                    '15' => '15',
                    '16' => '16',
                    '17' => '17',
                    '18' => '18',
                    '19' => '19',
                    '20' => '20',
                    '21' => '21',
                    '22' => '22',
                    '23' => '23',
                    '24' => '24',
                    '25' => '25',
                    '26' => '26',
                    '27' => '27',
                    '28' => '28',
                    '29' => '29',
                    '30' => '30',
                ],
                'default' => '-1',
            ],
            'zePrintRate' => [
                'name' => 'Print Rate',
                'values' => [
                    'Default' => 'Printer Default',
                    '1' => '1 inch/sec.',
                    '2' => '2 inches/sec.',
                    '3' => '3 inches/sec.',
                    '4' => '4 inches/sec.',
                    '5' => '5 inches/sec.',
                    '6' => '6 inches/sec.',
                    '7' => '7 inches/sec.',
                    '8' => '8 inches/sec.',
                    '9' => '9 inches/sec.',
                    '10' => '10 inches/sec.',
                    '11' => '11 inches/sec.',
                    '12' => '12 inches/sec.',
                ],
                'default' => 'Default',
            ],
            'zeLabelTop' => [
                'name' => 'Label Top',
                'values' => [
                    '200' => 'Printer Default',
                    '-120' => '-120',
                    '-115' => '-115',
                    '-110' => '-110',
                    '-105' => '-105',
                    '-100' => '-100',
                    '-95' => '-95',
                    '-90' => '-90',
                    '-85' => '-85',
                    '-80' => '-80',
                    '-75' => '-75',
                    '-70' => '-70',
                    '-65' => '-65',
                    '-60' => '-60',
                    '-55' => '-55',
                    '-50' => '-50',
                    '-45' => '-45',
                    '-40' => '-40',
                    '-35' => '-35',
                    '-30' => '-30',
                    '-25' => '-25',
                    '-20' => '-20',
                    '-15' => '-15',
                    '-10' => '-10',
                    '-5' => '-5',
                    '0' => '0',
                    '5' => '5',
                    '10' => '10',
                    '15' => '15',
                    '20' => '20',
                    '25' => '25',
                    '30' => '30',
                    '35' => '35',
                    '40' => '40',
                    '45' => '45',
                    '50' => '50',
                    '55' => '55',
                    '60' => '60',
                    '65' => '65',
                    '70' => '70',
                    '75' => '75',
                    '80' => '80',
                    '85' => '85',
                    '90' => '90',
                    '95' => '95',
                    '100' => '100',
                    '105' => '105',
                    '110' => '110',
                    '115' => '115',
                    '120' => '120',
                ],
                'default' => '200',
            ],
            'zePrintMode' => [
                'name' => 'Print Mode',
                'values' => [
                    'Saved' => 'Printer Default',
                    'Tear' => 'Tear-Off',
                    'Peel' => 'Peel-Off',
                    'Rewind' => 'Rewind',
                    'Applicator' => 'Applicator',
                    'Cutter' => 'Cutter',
                ],
                'default' => 'Saved',
            ],
            'zeTearOffPosition' => [
                'name' => 'Tear-Off Adjust Position',
                'values' => [
                    '1000' => 'Printer Default',
                    '-120' => '-120',
                    '-115' => '-115',
                    '-110' => '-110',
                    '-105' => '-105',
                    '-100' => '-100',
                    '-95' => '-95',
                    '-90' => '-90',
                    '-85' => '-85',
                    '-80' => '-80',
                    '-75' => '-75',
                    '-70' => '-70',
                    '-65' => '-65',
                    '-60' => '-60',
                    '-55' => '-55',
                    '-50' => '-50',
                    '-45' => '-45',
                    '-40' => '-40',
                    '-35' => '-35',
                    '-30' => '-30',
                    '-25' => '-25',
                    '-20' => '-20',
                    '-15' => '-15',
                    '-10' => '-10',
                    '-5' => '-5',
                    '0' => '0',
                    '5' => '5',
                    '10' => '10',
                    '15' => '15',
                    '20' => '20',
                    '25' => '25',
                    '30' => '30',
                    '35' => '35',
                    '40' => '40',
                    '45' => '45',
                    '50' => '50',
                    '55' => '55',
                    '60' => '60',
                    '65' => '65',
                    '70' => '70',
                    '75' => '75',
                    '80' => '80',
                    '85' => '85',
                    '90' => '90',
                    '95' => '95',
                    '100' => '100',
                    '105' => '105',
                    '110' => '110',
                    '115' => '115',
                    '120' => '120',
                ],
                'default' => '1000',
            ],
            'zeErrorReprint' => [
                'name' => 'Reprint After Error',
                'values' => [
                    'Saved' => 'Printer Default',
                    'Always' => 'Always',
                    'Never' => 'Never',
                ],
                'default' => 'Saved',
            ],
        ];
        $printer->ppd_options_layout = [
            [
                'name' => 'General',
                'options' => [
                    'PageSize',
                    'Resolution',
                    'zeMediaTracking',
                    'MediaType',
                ],
            ],
            [
                'name' => 'Printer Settings',
                'options' => [
                    'Darkness',
                    'zePrintRate',
                    'zeLabelTop',
                    'zePrintMode',
                    'zeTearOffPosition',
                    'zeErrorReprint',
                ],
            ],
        ];
        $server->Printers()->save($printer);

        $printer = new Printer;
        $printer->uri = 'cups://ZD420c';
        $printer->name = 'Zebra ZD420c (CUPS)';
        $printer->raw_languages_supported = ['zpl'];
        $printer->ppd_support = true;
        $printer->ppd_options = [
            'PageSize' => [
                'name' => 'Media Size',
                'values' => [
                    'w90h18' => '1.25x0.25"',
                    'w90h162' => '1.25x2.25"',
                    'w108h18' => '1.50x0.25"',
                    'w108h36' => '1.50x0.50"',
                    'w108h72' => '1.50x1.00"',
                    'w108h144' => '1.50x2.00"',
                    'w144h26' => '2.00x0.37"',
                    'w144h36' => '2.00x0.50"',
                    'w144h72' => '2.00x1.00"',
                    'w144h90' => '2.00x1.25"',
                    'w144h288' => '2.00x4.00"',
                    'w144h396' => '2.00x5.50"',
                    'w162h36' => '2.25x0.50"',
                    'w162h90' => '2.25x1.25"',
                    'w162h288' => '2.25x4.00"',
                    'w162h396' => '2.25x5.50"',
                    'w171h396' => '2.38x5.50"',
                    'w180h72' => '2.50x1.00"',
                    'w180h144' => '2.50x2.00"',
                    'w198h90' => '2.75x1.25"',
                    'w216h72' => '3.00x1.00"',
                    'w216h90' => '3.00x1.25"',
                    'w216h144' => '3.00x2.00"',
                    'w216h216' => '3.00x3.00"',
                    'w216h360' => '3.00x5.00"',
                    'w234h144' => '3.25x2.00"',
                    'w234h360' => '3.25x5.00"',
                    'w234h396' => '3.25x5.50"',
                    'w234h419' => '3.25x5.83"',
                    'w234h563' => '3.25x7.83"',
                    'w252h72' => '3.50x1.00"',
                    'w288h72' => '4.00x1.00"',
                    'w288h144' => '4.00x2.00"',
                    'w288h180' => '4.00x2.50"',
                    'w288h216' => '4.00x3.00"',
                    'w288h288' => '4.00x4.00"',
                    'w288h360' => '4.00x5.00"',
                    'w288h432' => '4.00x6.00"',
                    'w288h468' => '4.00x6.50"',
                    'w288h936' => '4.00x13.00"',
                    'w432h72' => '6.00x1.00"',
                    'w432h144' => '6.00x2.00"',
                    'w432h216' => '6.00x3.00"',
                    'w432h288' => '6.00x4.00"',
                    'w432h360' => '6.00x5.00"',
                    'w432h432' => '6.00x6.00"',
                    'w432h468' => '6.00x6.50"',
                    'w576h72' => '8.00x1.00"',
                    'w576h144' => '8.00x2.00"',
                    'w576h216' => '8.00x3.00"',
                    'w576h288' => '8.00x4.00"',
                    'w576h360' => '8.00x5.00"',
                    'w576h432' => '8.00x6.00"',
                    'w576h468' => '8.00x6.50"',
                    'Custom.WIDTHxHEIGHT' => 'Custom',
                ],
                'default' => 'w144h288',
            ],
            'Resolution' => [
                'name' => 'Resolution',
                'values' => [
                    '203dpi' => '203dpi',
                    '300dpi' => '300dpi',
                    '600dpi' => '600dpi',
                ],
                'default' => '600dpi',
            ],
            'zeMediaTracking' => [
                'name' => 'Media Tracking',
                'values' => [
                    'Continuous' => 'Continuous',
                    'Web' => 'Non-continuous (Web sensing)',
                    'Mark' => 'Non-continuous (Mark sensing)',
                ],
                'default' => 'Web',
            ],
            'MediaType' => [
                'name' => 'Media Type',
                'values' => [
                    'Saved' => 'Printer Default',
                    'Thermal' => 'Thermal Transfer Media',
                    'Direct' => 'Direct Thermal Media',
                ],
                'default' => 'Direct',
            ],
            'Darkness' => [
                'name' => 'Darkness',
                'values' => [
                    '-1' => 'Printer Default',
                    '1' => '1',
                    '2' => '2',
                    '3' => '3',
                    '4' => '4',
                    '5' => '5',
                    '6' => '6',
                    '7' => '7',
                    '8' => '8',
                    '9' => '9',
                    '10' => '10',
                    '11' => '11',
                    '12' => '12',
                    '13' => '13',
                    '14' => '14',
                    '15' => '15',
                    '16' => '16',
                    '17' => '17',
                    '18' => '18',
                    '19' => '19',
                    '20' => '20',
                    '21' => '21',
                    '22' => '22',
                    '23' => '23',
                    '24' => '24',
                    '25' => '25',
                    '26' => '26',
                    '27' => '27',
                    '28' => '28',
                    '29' => '29',
                    '30' => '30',
                ],
                'default' => '-1',
            ],
            'zePrintRate' => [
                'name' => 'Print Rate',
                'values' => [
                    'Default' => 'Printer Default',
                    '1' => '1 inch/sec.',
                    '2' => '2 inches/sec.',
                    '3' => '3 inches/sec.',
                    '4' => '4 inches/sec.',
                    '5' => '5 inches/sec.',
                    '6' => '6 inches/sec.',
                    '7' => '7 inches/sec.',
                    '8' => '8 inches/sec.',
                    '9' => '9 inches/sec.',
                    '10' => '10 inches/sec.',
                    '11' => '11 inches/sec.',
                    '12' => '12 inches/sec.',
                ],
                'default' => 'Default',
            ],
            'zeLabelTop' => [
                'name' => 'Label Top',
                'values' => [
                    '200' => 'Printer Default',
                    '-120' => '-120',
                    '-115' => '-115',
                    '-110' => '-110',
                    '-105' => '-105',
                    '-100' => '-100',
                    '-95' => '-95',
                    '-90' => '-90',
                    '-85' => '-85',
                    '-80' => '-80',
                    '-75' => '-75',
                    '-70' => '-70',
                    '-65' => '-65',
                    '-60' => '-60',
                    '-55' => '-55',
                    '-50' => '-50',
                    '-45' => '-45',
                    '-40' => '-40',
                    '-35' => '-35',
                    '-30' => '-30',
                    '-25' => '-25',
                    '-20' => '-20',
                    '-15' => '-15',
                    '-10' => '-10',
                    '-5' => '-5',
                    '0' => '0',
                    '5' => '5',
                    '10' => '10',
                    '15' => '15',
                    '20' => '20',
                    '25' => '25',
                    '30' => '30',
                    '35' => '35',
                    '40' => '40',
                    '45' => '45',
                    '50' => '50',
                    '55' => '55',
                    '60' => '60',
                    '65' => '65',
                    '70' => '70',
                    '75' => '75',
                    '80' => '80',
                    '85' => '85',
                    '90' => '90',
                    '95' => '95',
                    '100' => '100',
                    '105' => '105',
                    '110' => '110',
                    '115' => '115',
                    '120' => '120',
                ],
                'default' => '200',
            ],
            'zePrintMode' => [
                'name' => 'Print Mode',
                'values' => [
                    'Saved' => 'Printer Default',
                    'Tear' => 'Tear-Off',
                    'Peel' => 'Peel-Off',
                    'Rewind' => 'Rewind',
                    'Applicator' => 'Applicator',
                    'Cutter' => 'Cutter',
                ],
                'default' => 'Saved',
            ],
            'zeTearOffPosition' => [
                'name' => 'Tear-Off Adjust Position',
                'values' => [
                    '1000' => 'Printer Default',
                    '-120' => '-120',
                    '-115' => '-115',
                    '-110' => '-110',
                    '-105' => '-105',
                    '-100' => '-100',
                    '-95' => '-95',
                    '-90' => '-90',
                    '-85' => '-85',
                    '-80' => '-80',
                    '-75' => '-75',
                    '-70' => '-70',
                    '-65' => '-65',
                    '-60' => '-60',
                    '-55' => '-55',
                    '-50' => '-50',
                    '-45' => '-45',
                    '-40' => '-40',
                    '-35' => '-35',
                    '-30' => '-30',
                    '-25' => '-25',
                    '-20' => '-20',
                    '-15' => '-15',
                    '-10' => '-10',
                    '-5' => '-5',
                    '0' => '0',
                    '5' => '5',
                    '10' => '10',
                    '15' => '15',
                    '20' => '20',
                    '25' => '25',
                    '30' => '30',
                    '35' => '35',
                    '40' => '40',
                    '45' => '45',
                    '50' => '50',
                    '55' => '55',
                    '60' => '60',
                    '65' => '65',
                    '70' => '70',
                    '75' => '75',
                    '80' => '80',
                    '85' => '85',
                    '90' => '90',
                    '95' => '95',
                    '100' => '100',
                    '105' => '105',
                    '110' => '110',
                    '115' => '115',
                    '120' => '120',
                ],
                'default' => '1000',
            ],
            'zeErrorReprint' => [
                'name' => 'Reprint After Error',
                'values' => [
                    'Saved' => 'Printer Default',
                    'Always' => 'Always',
                    'Never' => 'Never',
                ],
                'default' => 'Saved',
            ],
        ];
        $printer->ppd_options_layout = [
            [
                'name' => 'General',
                'options' => [
                    'PageSize',
                    'Resolution',
                    'zeMediaTracking',
                    'MediaType',
                ],
            ],
            [
                'name' => 'Printer Settings',
                'options' => [
                    'Darkness',
                    'zePrintRate',
                    'zeLabelTop',
                    'zePrintMode',
                    'zeTearOffPosition',
                    'zeErrorReprint',
                ],
            ],
        ];
        $server->Printers()->save($printer);

        $printer = new Printer;
        $printer->uri = 'cups://HP_LaserJet_400';
        $printer->name = 'HP LaserJet 400 (CUPS)';
        $printer->raw_languages_supported = ['pcl', 'postscript', 'pdf'];
        $printer->ppd_support = true;
        $printer->ppd_options = [
            'PageSize' => [
                'name' => 'Media Size',
                'values' => [
                    'Letter' => 'US Letter',
                    'Legal' => 'US Legal',
                    'Executive' => 'Executive',
                    'FanFoldGermanLegal' => '8.5x13',
                    'A4' => 'A4',
                    'A5' => 'A5',
                    'A6' => 'A6',
                    'B5' => 'JIS B5',
                    '195x270mm' => '16K 195x270 mm',
                    '184x260mm' => '16K 184x260 mm',
                    '7.75x10.75' => '16K 197x273 mm',
                    'Postcard' => 'Postcard',
                    'DoublePostcardRotated' => 'Postcard Double Long Edge',
                    'Env10' => 'Envelope #10',
                    'EnvMonarch' => 'Envelope Monarch',
                    'EnvISOB5' => 'Envelope B5',
                    'EnvC5' => 'Envelope C5',
                    'EnvDL' => 'Envelope DL',
                    'Custom.WIDTHxHEIGHT' => 'Custom',
                ],
                'default' => 'A4',
            ],
            'InputSlot' => [
                'name' => 'Paper Source',
                'values' => [
                    'Tray1' => 'Tray 1',
                    'Tray2' => 'Tray 2',
                    'Tray3' => 'Tray 3',
                    'Tray1_Man' => 'Tray 1 (Manual)',
                ],
                'default' => 'Tray1',
            ],
            'Duplex' => [
                'name' => 'Two-Sided',
                'values' => [
                    'None' => 'Off',
                    'DuplexNoTumble' => 'Long-Edge Binding',
                    'DuplexTumble' => 'Short-Edge Binding',
                ],
                'default' => 'None',
            ],
            'MediaType' => [
                'name' => '',
                'values' => [
                    'Unspecified' => 'Unspecified',
                    'Plain' => 'Plain',
                    'HPEcoSMARTLite' => 'HP EcoSMART Lite',
                    'Light6074' => 'Light 60-74g',
                    'MidWeight96110' => 'Mid-Weight 96-110g',
                    'Heavy111130' => 'Heavy 111-130g',
                    'ExtraHeavy131175' => 'Extra Heavy 131-175g',
                    'MonochromeLaserTransparency' => 'Monochrome Laser Transparency',
                    'Labels' => 'Labels',
                    'Letterhead' => 'Letterhead',
                    'Envelope' => 'Envelope',
                    'Preprinted' => 'Preprinted',
                    'Prepunched' => 'Prepunched',
                    'Colored' => 'Colored',
                    'Bond' => 'Bond',
                    'Recycled' => 'Recycled',
                    'Rough' => 'Rough',
                ],
                'default' => 'Unspecified',
            ],
            'HPPrintQuality' => [
                'name' => 'Print Quality',
                'values' => [
                    'FastRes1200' => 'FastRes 1200',
                    '600dpi' => '600 dpi',
                    'ProRes1200' => 'ProRes 1200',
                ],
                'default' => 'FastRes1200',
            ],
            'HPOption_Duplexer' => [
                'name' => 'Duplex Unit',
                'values' => [
                    'True' => 'True',
                    'False' => 'False',
                ],
                'default' => 'True',
            ],
            'HPOption_Tray3' => [
                'name' => 'Tray 3',
                'values' => [
                    'False' => 'False',
                    'True' => 'True',
                ],
                'default' => 'True',
            ],
            'HPManualDuplexSwitch' => [
                'name' => 'Manual Duplex',
                'values' => [

                    'True' => 'On',
                    'False' => 'Off',
                ],
                'default' => 'False',
            ],
            'HPManualDuplexPrintGuide' => [
                'name' => 'Print Reinsertion Guide',
                'values' => [
                    'True' => 'On',
                    'False' => 'Off',
                ],
                'default' => 'False',
            ],
            'HPManualDuplexOrientation' => [
                'name' => 'Binding',
                'values' => [
                    'DuplexNoTumble' => 'Long-Edge Binding',
                    'DuplexTumble' => 'Short-Edge Binding',
                ],
                'default' => 'DuplexNoTumble',
            ],
            'HPEconoMode' => [
                'name' => 'EconoMode',
                'values' => [
                    'True' => 'On',
                    'False' => 'Off',
                ],
                'default' => 'False',
            ],
            'HPBookletPageSize' => [
                'name' => 'Paper for Booklet',
                'values' => [
                    '184x260mm' => '16K 184x260 mm',
                    '195x270mm' => '16K 195x270 mm',
                    '7.75x10.75' => '16K 197x273 mm',
                    'A4' => 'A4',
                    'A5' => 'A5',
                    'A6' => 'A6',
                    'B5' => 'B5 (JIS)',
                    'DoublePostcardRotated' => 'Double Postcard (JIS)',
                    'Executive' => 'Executive',
                    'FanFoldGermanLegal' => '8.5x13',
                    'Legal' => 'US Legal',
                    'Letter' => 'US Letter',
                    'Postcard' => 'Postcard (JIS)',
                ],
                'default' => 'A4',
            ],
            'HPwmSwitch' => [
                'name' => 'Watermark',
                'values' => [
                    'True' => 'On',
                    'False' => 'Off',
                ],
                'default' => 'False',
            ],
            'HPwmPages' => [
                'name' => 'Pages',
                'values' => [
                    'AllPages' => 'All Pages',
                    'FirstPage' => 'First Only',
                ],
                'default' => 'AllPages',
            ],
            'HPwmTextMessage' => [
                'name' => 'Text',
                'values' => [
                    'Draft' => 'Draft',
                    'CompanyConfidential' => 'Company Confidential',
                    'CompanyProprietary' => 'Company Proprietary',
                    'CompanyPrivate' => 'Company Private',
                    'Confidential' => 'Confidential',
                    'Copy' => 'Copy',
                    'Copyright' => 'Copyright',
                    'FileCopy' => 'File Copy',
                    'Final' => 'Final',
                    'ForInternalUse' => 'For Internal Use Only',
                    'Preliminary' => 'Preliminary',
                    'Proof' => 'Proof',
                    'ReviewCopy' => 'Review Copy',
                    'Sample' => 'Sample',
                    'TopSecret' => 'Top Secret',
                    'Urgent' => 'Urgent',
                    'Custom' => 'Text',
                ],
                'default' => 'Draft',
            ],
            'HPwmFontName' => [
                'name' => 'Font',
                'values' => [
                    'CourierB' => 'Courier Bold',
                    'HelveticaB' => 'Helvetica Bold',
                    'TimesB' => 'Times Bold',
                ],
                'default' => 'HelveticaB',
            ],
            'HPwmFontSize' => [
                'name' => 'Size',
                'values' => [
                    'pt24' => '24',
                    'pt30' => '30',
                    'pt36' => '36',
                    'pt42' => '42',
                    'pt48' => '48',
                    'pt54' => '54',
                    'pt60' => '60',
                    'pt66' => '66',
                    'pt72' => '72',
                    'pt78' => '78',
                    'pt84' => '84',
                    'pt90' => '90',
                ],
                'default' => 'pt48',
            ],
            'HPwmTextAngle' => [
                'name' => 'Angle',
                'values' => [
                    'Deg90' => '90 degrees',
                    'Deg75' => '75 degrees',
                    'Deg60' => '60 degrees',
                    'Deg45' => '45 degrees',
                    'Deg30' => '30 degrees',
                    'Deg15' => '15 degrees',
                    'Deg0' => '0 degrees',
                    'DegN15' => '-15 degrees',
                    'DegN30' => '-30 degrees',
                    'DegN45' => '-45 degrees',
                    'DegN60' => '-60 degrees',
                    'DegN75' => '-75 degrees',
                    'DegN90' => '-90 degrees',
                ],
                'default' => 'Deg45',
            ],
            'HPwmTextStyle' => [
                'name' => 'Style',
                'values' => [
                    'Thin' => 'Thin Outline',
                    'Medium' => 'Medium Outline',
                    'Thick' => 'Thick Outline',
                    'Halo' => 'Thick Outline with Halo',
                    'Fill' => 'Filled',
                ],
                'default' => 'Medium',
            ],
            'HPwmBrightness' => [
                'name' => 'Intensity',
                'values' => [
                    'Darkest' => 'Darkest',
                    'Darker' => 'Very Dark',
                    'Dark' => 'Dark',
                    'MediumDark' => 'Medium Dark',
                    'Medium' => 'Medium',
                    'MediumLight' => 'Medium Light',
                    'Light' => 'Light',
                    'Lighter' => 'Very Light',
                    'Lightest' => 'Lightest',
                ],
                'default' => 'Medium',
            ],
            'HPBookletFilter' => [
                'name' => 'Format Output as Booklet',
                'values' => [
                    'True' => 'On',
                    'False' => 'Off',
                ],
                'default' => 'False',
            ],
            'HPBookletPageOrder' => [
                'name' => 'Bind Pages on the Right',
                'values' => [
                    'True' => 'On',
                    'False' => 'Off',
                ],
                'default' => 'False',
            ],
            'HPBookletBackCover' => [
                'name' => 'Last Page Is Back Cover',
                'values' => [
                    'True' => 'On',
                    'False' => 'Off',
                ],
                'default' => 'False',
            ],
            'HPBookletScaling' => [
                'name' => 'Scaling',
                'values' => [
                    'Proportional' => 'Proportional',
                    'FitPage' => 'To Fit Page Size',
                ],
                'default' => 'Proportional',
            ],
        ];
        $printer->ppd_options_layout = [
            [
                'name' => 'General',
                'options' => [
                    'PageSize',
                    'InputSlot',
                    'Duplex',
                    'MediaType',
                    'HPPrintQuality',
                ],
            ],
            [
                'name' => 'Installed Options',
                'options' => [
                    'HPOption_Duplexer',
                    'HPOption_Tray3',
                ],
            ],
            [
                'name' => 'Manual Duplex',
                'options' => [
                    'HPManualDuplexSwitch',
                    'HPManualDuplexPrintGuide',
                    'HPManualDuplexOrientation',
                ],
            ],
            [
                'name' => 'Paper/Quality',
                'options' => [
                    'HPEconoMode',
                    'HPBookletPageSize',
                ],
            ],
            [
                'name' => 'Watermarks',
                'options' => [
                    'HPwmSwitch',
                    'HPwmPages',
                    'HPwmTextMessage',
                    'HPwmFontName',
                    'HPwmFontSize',
                    'HPwmTextAngle',
                    'HPwmTextStyle',
                    'HPwmBrightness',
                ],
            ],
            [
                'name' => 'Booklet Printing',
                'options' => [
                    'HPBookletFilter',
                    'HPBookletPageOrder',
                    'HPBookletBackCover',
                    'HPBookletScaling',
                ],
            ],
        ];
        $server->Printers()->save($printer);
    }
}
